[package]
name = "duolingo-rustapi"
version = "0.1.0"
authors = ["zero-systems <zerosystems@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
